/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:1f42a853-ddfa-4e0f-ba4c-5eb8599197e3",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_0Vr2aI6aG",
    "aws_user_pools_web_client_id": "1uvtcgb5toqp5oqtpsn1irgbhs",
    "oauth": {}
};


export default awsmobile;
